service: emailsender
provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1

package:
  exclude:
    - .gitignore
    - .git/**
    - tests/**

functions:
  app:
    handler: src/appHandler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
